### ISSUE TITLE
Eclipse Java EE IDE for Web Developers.  Version: Mars.2 Release (4.5.2)

### ISSUE THREAD

**Issue by yangxiaoyi-git** [Jamling/SmartQQ4Eclipse#10]
Plug-in cn.ieclipse.smartqq was unable to load class cn.ieclipse.smartqq.views.ContactView.
org.eclipse.core.runtime.CoreException: Plug-in cn.ieclipse.smartqq was unable to load class cn.ieclipse.smartqq.views.ContactView.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.ui.internal.registry.ViewDescriptor.createView(ViewDescriptor.java:58)

**Comment by Jamling** [comment]
我了个去，你这个issue牛批了，竟然找不到联系人列表view。告诉我你的eclipse版本信息及jre信息吧。在Windows->Preference->SmartQQ里。复制即可
