### ISSUE TITLE
spring sts 不支持

### ISSUE THREAD

**Issue by tonggangjin** [Jamling/SmartQQ4Eclipse#16]
发送信息时提示参数错误，但是实际能发送，微信二维码看不到
版本信息如下：
Spring Tool Suite 

Version: 3.9.2.RELEASE
Build Id: 201712210947
Platform: Eclipse Oxygen.2 (4.7.2)

**Comment by Jamling** [comment]
请提供详细的日志（在Error Log里）及smartqq版本信息。

**Comment by tonggangjin** [comment]
版本信息：
Platform:
● Spring Tool Suite(3.9.2.201712210947-RELEASE):active
Host plugin:
● SmartQQ(2.1.2):active

我不知道日志在哪里

**Comment by tonggangjin** [comment]
发信QQ信息的时候有这个错误：
An error has occurred. See error log for more details.
Argument not valid

**Comment by Jamling** [comment]
Window->Show View->Error Log，可以打开错误视图。

**Comment by tonggangjin** [comment]
登录的时候错误如下：
cn.ieclipse.smartim.exception.LogicException: 请求失败，Api返回码[100003]
	at com.scienjus.smartqq.client.SmartQQApi.getResponseJson(SmartQQApi.java:589)
	at com.scienjus.smartqq.client.SmartQQApi.getJsonObjectResult(SmartQQApi.java:534)
	at com.scienjus.smartqq.client.SmartQQApi.getFriendListWithCategory(SmartQQApi.java:370)
	at com.scienjus.smartqq.client.SmartQQClient.init(SmartQQClient.java:216)
	at cn.ieclipse.smartqq.views.QQContactView.doLoadContacts(QQContactView.java:69)
	at cn.ieclipse.smartim.views.IMContactView$1.run(IMContactView.java:77)

**Comment by tonggangjin** [comment]
今天不能登录了，看样子是腾讯那边出了问题

**Comment by Jamling** [comment]
@tonggangjin 尝试在[腾讯SmartQQ官网](https://web2.qq.com)看能否登录，记得关闭时手动退出WebQQ。我的账号已经登录不了了。

**Comment by tonggangjin** [comment]
官方也不能登录了

**Comment by Jamling** [comment]
腾讯的SmartQQ不稳定，估计没人维护，我已经反馈过问题了。
准备放弃SmartQQ了，现在正在抓紧完善微信功能，SmartQQ用不了了，就上微信 😃

**Comment by tonggangjin** [comment]
好

**Comment by tonggangjin** [comment]
但是现在 微信用不了啊

**Comment by Jamling** [comment]
仔细看README和日志。

**Comment by tonggangjin** [comment]
我看到了，加了那个，现在二维码出来了
刚刚试了试，ok

**Comment by XiaoWH** [comment]
eclipse是luna版本  消息发送成功了  但是没法接收消息
查看日志是这样的：
eclipse.buildId=4.4.0.I20140606-1215
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

cn.ieclipse.smartqq
Warning
Tue May 22 10:09:44 CST 2018
添加聊天记录 10:09:44 ****: 木想到只能发  不能看 失败，估计您的浏览器内核（ie）太低，请尝试升级浏览器后再试

**Comment by Jamling** [comment]
估计是你的ie版本太低了，你是ie几？
