### ISSUE TITLE
发现QQ和微信都不能用了

### ISSUE THREAD

**Issue by ViCrack** [Jamling/SmartQQ4Eclipse#33]
> eclipse.buildId=4.14.0.I20191210-0610
> java.version=1.8.0_202
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
> Framework arguments:  -product org.eclipse.epp.package.jee.product
> Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

<img width="487" alt="1111" src="https://user-images.githubusercontent.com/18179821/72310455-c845f180-36bc-11ea-92cc-f030028305ee.png">
<img width="459" alt="We" src="https://user-images.githubusercontent.com/18179821/72310457-c8de8800-36bc-11ea-803e-8e907002419f.png">

```


java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Unknown Source)
	at java.lang.Long.valueOf(Unknown Source)
	at io.github.biezhi.wechat.api.WechatApi.login(WechatApi.java:270)
	at io.github.biezhi.wechat.api.WechatClient.login(WechatClient.java:114)
	at cn.ieclipse.smartim.dialogs.LoginDialog.doLogin(LoginDialog.java:167)
	at cn.ieclipse.smartim.dialogs.LoginDialog$1.run(LoginDialog.java:63)
```

<img width="557" alt="1" src="https://user-images.githubusercontent.com/18179821/72310550-fd524400-36bc-11ea-8347-9c494fc3022a.png">

```

java.net.UnknownHostException: s.web2.qq.com
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(Unknown Source)
	at java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.net.InetAddress.getAllByName0(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at okhttp3.Dns$1.lookup(Dns.java:39)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:137)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:82)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:171)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at com.scienjus.smartqq.client.SmartQQApi.get(SmartQQApi.java:505)
	at com.scienjus.smartqq.client.SmartQQApi.getVfwebqq(SmartQQApi.java:211)
	at com.scienjus.smartqq.client.SmartQQApi.login(SmartQQApi.java:111)
	at com.scienjus.smartqq.client.SmartQQClient.login(SmartQQClient.java:195)
	at cn.ieclipse.smartim.dialogs.LoginDialog.doLogin(LoginDialog.java:167)
	at cn.ieclipse.smartim.dialogs.LoginDialog$1.run(LoginDialog.java:63)


```

**Comment by Jamling** [comment]
QQ去年1月1日就停止服务了。微信许多账号被限制了登录

**Comment by ViCrack** [comment]
> 
> 
> QQ去年1月1日就停止服务了。微信许多账号被限制了登录

那真是可惜, 许久没用了
