### ISSUE TITLE
登录后联系人、群、讨论组等信息，都没有

### ISSUE THREAD

**Issue by chaoliu1995** [Jamling/SmartQQ4Eclipse#8]
登录之后，联系人、群、讨论组等信息，都没有。

![default](https://user-images.githubusercontent.com/16618592/29702962-108b4f56-89a6-11e7-96db-4c541bef8d5b.png)

Broadcast Message功能可以使用（说明登录成功）。

Eclispe Version: Oxygen Release (4.7.0)
Build id: 20170620-1800

SmartQQ(1.0.9):active

**Comment by Jamling** [comment]
请尝试
1，点击扫码登录，然后点击取消重新加载联系人。
2，断开连接后重新扫码登录。

PS：从你的issue内容来看，你对eclipse很熟啊。

**Comment by chaoliu1995** [comment]
呃......，也不太熟，Eclips是主要开发工具，和你这样开发插件的可比不了，*@_@*

我试了三四次还是不行，这个版本也试了: Eclispe Neon.3 Release (4.6.3) Build id: 20170314-1500，也不行。

我看了一下Eclipse的日志文件：

`!ENTRY cn.ieclipse.smartqq 4 0 2017-08-29 08:52:14.378
!MESSAGE 初始化失败java.io.IOException: 请求失败，Api返回码[1202]

!ENTRY cn.ieclipse.smartqq 4 0 2017-08-29 08:55:47.919
!MESSAGE 初始化失败java.io.IOException: 请求失败，Api返回码[1202]

!ENTRY org.eclipse.ui 4 0 2017-08-29 08:56:45.208
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
	at org.eclipse.swt.widgets.Text.setText(Text.java:2311)
	at cn.ieclipse.smartqq.views.LoginDialog$1$1$2.run(LoginDialog.java:105)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)`

和操作系统有关系吗？我是win7的系统（公司的机子）

**Comment by Jamling** [comment]
跟系统与eclipse没有关系。你试着去官网http://w.qq.com正常登录一次，然后退出。再回来eclipse登录。

**Comment by chaoliu1995** [comment]
刚刚在web登录了一下，退出，回到eclipse，扫码登录，还和之前一样，登录是成功了，群发消息可以看到好友信息：
![default](https://user-images.githubusercontent.com/16618592/29800903-2f76e316-8c9f-11e7-85d3-2f9712d6db4b.png)

但是，还和之前一样：
![default](https://user-images.githubusercontent.com/16618592/29800920-560a8f00-8c9f-11e7-8489-30a5d23d84cb.png)

日志：
!ENTRY cn.ieclipse.smartqq 4 0 2017-08-29 09:42:11.822
!MESSAGE 初始化失败java.io.IOException: 请求失败，Api返回码[1202]

**Comment by Jamling** [comment]
1202 的api常见于发送消息。初始化都是读取列表操作。这就不清楚了。smart qq协议并不是十分稳定。过几天再试试吧。

**Comment by chaoliu1995** [comment]
好的

**Comment by ydq** [comment]
上次在osc上面看到这个插件就尝试了，和LZ一样的情况，可以广播，但console中无列表，如今过了这么久了，再一次的尝试，还是这个情况。

**Comment by Jamling** [comment]
@ydq 还是1202的错误代码吗？在eclipse中的Error Log中可以看到详细的错误日志
